steps:
    - id: 'branch name'
      name: 'alpine'
      entrypoint: 'sh'  
      args: 
      - '-c'
      - | 
          echo "-----------------------"
          echo "Deploying to branch $BRANCH_NAME"
          echo "-----------------------"
    
    - id: 'tf init'
      name: 'hashicorp/terraform:0.12.9'
      entrypoint: 'sh'
      args: 
      - '-c'
      - |
          if [ -d "envs/$BRANCH_NAME/" ]; then
            cd envs/$BRANCH_NAME
            terraform init
          else
            for dir in envs/*/
            do 
              cd ${dir}   
              env=${dir%*/}
              env=${env#*/}
              echo ""
              echo "------------ TERRAFORM INIT ------------"
              echo "------- Environment: ${env} ------------"
              echo "----------------------------------------"
              terraform init || exit 1
              cd ../../
            done
          fi 
    
    # [terraform plan]
    - id: 'tf plan'
      name: 'hashicorp/terraform:0.12.9'
      entrypoint: 'sh'
      args: 
      - '-c'
      - | 
          if [ -d "envs/$BRANCH_NAME/" ]; then
            cd envs/$BRANCH_NAME
            terraform plan
          else
            for dir in envs/*/
            do 
              cd ${dir}   
              env=${dir%*/}
              env=${env#*/}  
              echo ""
              echo "------------ TERRAFOM PLAN ------------"
              echo "------------ At environment: ${env} ------------"
              echo "----------------------------------------"
              terraform plan || exit 1
              cd ../../
            done
          fi 
    
    # [terraform apply]
    - id: 'tf apply'
      name: 'hashicorp/terraform:0.12.9'
      entrypoint: 'sh'
      args: 
      - '-c'
      - | 
          if [ -d "envs/$BRANCH_NAME/" ]; then
            cd envs/$BRANCH_NAME      
            terraform apply -auto-approve
          else
            echo "------------ SKIP APPLY ------------"
            echo "Skipped apply for branch '$BRANCH_NAME' "
            echo ""----------------------------------------""
          fi      
    